import bcrypt from 'bcryptjs'

const data = {
    users: [
        {
            name: 'Admin',
            email: 'admin@amazona.com',
            password: bcrypt.hashSync('1234', 8),
            isSeller: true,
            isAdmin: true,
            seller: {
                name: 'Teste',
                logo: '/images/logo.png',
                description: 'Best Seller',
                rating: 4.5,
                numReviews: 120,
            },
        },
        {
            name: 'User',
            email: 'user@amazona.com',
            password: bcrypt.hashSync('1234', 8),
            isSeller: false,
            isAdmin: false,
            seller: {
                name: 'Teste',
                logo: '/images/logo.png',
                description: 'Best Seller',
                rating: 4.5,
                numReviews: 120,
            },
        },
    ],
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quaity product',
            countInStock: 10,
            reviews: [],
        },
        {
            name: 'Nike Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quaity product',
            countInStock: 20,
            reviews: [],
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quaity product',
            countInStock: 0,
            reviews: [],
        },
        {
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quaity product',
            countInStock: 15,
            reviews: [],
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quaity product',
            countInStock: 5,
            reviews: [],
        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quaity product',
            countInStock: 12,
            reviews: [],
        },
    ],
}

export default data
